---
title: "Kmeans"
author: "Bill Lang"
date: "7/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggmap)
```



```{r}
load(file = "boston.RData")
boston
```


```{r}
boston$Area <- tolower(boston$Area)
boston$Street <- tolower(boston$Street)
boston <- boston %>% unite(Address, c("Hse.No","Street","Area"), sep = " ",remove = FALSE)
boston$Address <- paste(boston$Address, ", MA")
boston
```

Geocoding and saving the files same as before. 
 
```{r}
#geocoded <- tidygeocoder::geocode(.tbl = boston, address = Address, method = "osm", lat = latitude, long = longitude)
```


```{r}
load(file = "allBoston.RData")
geocoded 
```

```{r}
geocoded <- geocoded %>% select(Year,Month,Date,Price.type,Total.rooms,Column,Area,Hse.No,Street,Cross.Street,Address,Type,latitude,longitude)

geocoded$Price.type <- tolower(geocoded$Price.type)
geocoded$Price.type <- as.factor(geocoded$Price.type)

geocoded$Type <- tolower(geocoded$Type)

geocoded$Column <- tolower(geocoded$Column)
geocoded$Type <- as.factor(geocoded$Type)
geocoded$Total.rooms <- as.integer(geocoded$Total.rooms)
geocoded <- geocoded

#5 is the mean of totalrooms
geocoded <- geocoded %>% mutate(Total.rooms = replace_na(Total.rooms,5))
geocoded
str(geocoded)
```


```{r}
k <- "AIzaSyDNMoGGfgl9f5KtGCnp9BegNb7ZDqPu7gg"
register_google(key = k)
```


```{r}
map <- get_map(location = 'Boston', zoom = 8, maptype = "terrain-background", source = 'google', color = 'color')
ggmap(map) + geom_point(data = geocoded, mapping = aes(x = longitude, y = latitude, color = factor(Area)), size = 1) + theme(legend.position = "none")
```

