---
title: "All Geocoded LA"
author: "Bill Lang"
date: "7/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggmap)
```


```{r}
load(file = "NY.RData")
ny
```


```{r}
ny$Area <- tolower(ny$Area)
ny$Street <- tolower(ny$Street)
ny$Street <- tolower(ny$Column.Location)
ny$Street <- tolower(ny$Area)
ny <- ny %>% unite(Address, c("Hse.No","Street","Area","Column.Location"), sep = " ",remove = FALSE)
ny$Address <- paste(ny$Address, "")
ny
```

Geocoding and saving the files same as before. 
 
```{r}
geocodedNY <- tidygeocoder::geocode(.tbl = ny, address = Address, method = "osm", lat = latitude, long = longitude)
save(geocodedNY, file = "allNY.RData")
```


```{r}
load(file = "allNY.RData")
geocodedNY 
geocodedNY$Street <- tolower(geocodedNY$Column.Location)
geocodedNY$Street <- tolower(geocodedNY$Area)
```


```{r}
incorrectMatches <- geocodedNY %>% filter((is.na(latitude) | (latitude < 38) | (latitude > 44) | (longitude < -78) | (longitude > -71)) )
```

```{r}
correctMatches <- geocodedNY %>% filter(!(is.na(latitude) | (latitude < 38) | (latitude > 44) | (longitude < -78) | (longitude > -71)) )
```


```{r}
k <- "AIzaSyDNMoGGfgl9f5KtGCnp9BegNb7ZDqPu7gg"
register_google(key = k)
```



```{r}
map <- get_map(location = 'New York', zoom = 7, maptype = "terrain-background", source = 'google', color = 'color')
ggmap(map) + geom_point(data = correctMatches, mapping = aes(x = longitude, y = latitude, color = factor(Column.Location)), size = 1) + theme(legend.position = "none")
```

