---
title: "Building Dataset Output New York"
author: "Bill Lang"
date: "9/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggmap)
```

Origional dataset

```{r}
load(file = "NY.RData")
ny
```

87000~ that we have geoinformation for from the data itself

```{r}
load(file = "cleanNY.RData")
load(file = "NYAreas.RData")
load(file = "predictedNY.RData")
NYDataExport <- NYData %>% filter(Coarse.Geo %in% listOfAreasNY)
NYDataExport <- NYDataExport %>% mutate(calculatedColumn = Column) %>% select(-Column)
#predicted file from the Testing Random Forest New York Set
#Making sure that the column names line up for the rbind function

predicted
predicted <- predicted %>% mutate(calculatedColumn = yhat.rf) %>% select(-yhat.rf) %>% select(-Column)
NYDataExport <- rbind(NYDataExport,predicted)
NYDataExport
```

Of the ones that the geocoder didn't find well, they can be classified manually with the availablilty of the data in the NY dataset

```{r}
incorrectMatches <- capitalizeRent(incorrectMatches)

pattern3 <- c("manhattan|westchester|newjersey|westside|eastside|queens|longisland|brooklyn|nassausuffolk|connecticut|bronx|queens& long island|newyork|westchestercounty|queenslongisland|statenisland")
incorrectMatches <- incorrectMatches %>% mutate(Coarse.Geo = ifelse(
  grepl(pattern3, Coarse.Geo, ignore.case = TRUE), as.character(Coarse.Geo), ""))

#sending section --> manhattan
incorrectMatches <- incorrectMatches %>%
  mutate(Coarse.Geo = case_when(
    str_detect(Coarse.Geo, "eastside") ~ "manhattan",
    str_detect(Coarse.Geo, "manhattanand bronx") ~ "manhattan",
    TRUE ~ Coarse.Geo
    )
  )
incorrectMatches <- incorrectMatches %>% mutate(calculatedColumn = Coarse.Geo)
```

Now we add these rows to the export file

```{r}
NYDataExport
incorrectMatches

NYDataExport <- rbind(NYDataExport, incorrectMatches)
NYDataExport
```


```{r}
write.csv(NYDataExport, file = "C:/Users/the36/Desktop/DataRA/RExports/nyExport.csv")
```

