---
title: "QDA, LDA"
author: "Bill Lang"
date: "6/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(class)
library(tree)
library(randomForest)
library(glmnet)
library(ggmap)
library(MASS)
```

```{r}
bostonArea <- geocodeFile %>% filter(!is.na(latitude))
bostonArea
```

LDA

```{r}
set.seed(343)

shuffleRows <- sample(nrow(bostonArea))
bostonArea <- bostonArea[shuffleRows,]
train <- sample(nrow(bostonArea)*.80)
bostonTrain <- bostonArea[train,]
bostonTest <- bostonArea[-train,]

length(unique(bostonArea$Area))
length(unique(bostonTrain$Area))
length(unique(bostonTest$Area))
```


```{r}
lda.fit <- lda(Area ~year+ totalrooms + type + latitude + longitude, data = bostonTrain)
lda.fit
```

```{r}
lda.pred <- predict(lda.fit, bostonTest)

lda.class <- lda.pred$class
options(max.print = 999999999)
table(observed = bostonTest$Area,predicted = lda.class)
```


```{r}
misclassRate <- mean(lda.class != bostonTest$Area)
misclassRate
```


```{r}
options(max.print = 999999999)
table(observed = bostonTest$target_no, predicted = yhat.rf)
```


QDA


```{r}
qda.fit <- MASS::qda(area ~year+ totalrooms + saleprice + rentprice + pricetype + type, data = bostonTrain)
qda.fit
```





