---
title: 'Off'
author: "Bill Lang"
date: "6/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidygeocoder)
library(ggmap)
```

Find all locations within a major area and/or an address geocode them.
Build model off of those coordianates.

```{r}
bostonCustom 
bostonTemp <- bostonCustom %>% filter(street != "" | crossstreet != "" | area != "")
bostonTemp
```

Sample 5000 observations, geocode, filter the coordiantes, build model

```{r}
geo <- bostonTemp %>% dplyr::select(target_no,year,month,date,page,totalrooms,pricetype, saleprice,rentprice, frequency, type, area, hseno, street) %>% mutate(Area = area)
geo <- geo %>% unite(address, c(hseno, street, area), sep = " ")
geo$address <- paste(geo$address, " , MA")
geo
```


```{r}
set.seed(11)
shuf <- sample(nrow(geo))
geo <- geo[shuf,]
geo

rows <- sample(1:1000)
temp <- geo[rows,]
temp
```


```{r}
geocodeFileFull <- tidygeocoder::geocode(.tbl = temp, address = address, method = "osm", lat = latitude, long = longitude)
geocodeFile <- geocodeFileFull
geocodeFile
geocodeFile %>% filter(is.na(latitude))
```


```{r}
k <- "AIzaSyDNMoGGfgl9f5KtGCnp9BegNb7ZDqPu7gg"
register_google(key = k)
```


```{r}
map <- get_map(location = 'Boston', zoom = 10, maptype = "terrain-background", source = 'google', color = 'color')
ggmap(map) + geom_point(data = geocodeFile, mapping = aes(x = longitude, y = latitude, color = factor(Area)), position = "jitter")
```


```{r}
dat <- geocodeFile %>% mutate_all(na_if,"")
dat$type <- as.factor(dat$type)
dat$pricetype <- as.factor(dat$pricetype)



dat2 <- rfImpute(target_no~ longitude + latitude + year + totalrooms + type +saleprice + rentprice + pricetype ,data = dat, iter = 6)

dat2
```


```{r}
geocodeFile <- na.omit(geocodeFile)
geocodeFile <- geocodeFile %>% filter(!longitude < -72) %>% filter(!latitude > 42.75)%>% filter(longitude < -70.8)%>% filter(latitude > 42.0)


write.csv(geocodeFile, file = "C:/Users/Billy/Desktop/Storage/lat2.csv")
geocodeFile <- read.csv("C:/Users/Billy/Desktop/Storage/lat2.csv")[,-1]
geocodeFile
```



```{r}
data <- bostonTemp
data <- data %>% unite(address, c(hseno, street, area), sep = " ")
data$address <- paste(data$address, " , MA")
data <- data %>% select(address,year,month,date,page,totalrooms, type,saleprice)

data
mod


mod <- mod %>% inner_join(data, by = c("address"="address"))
mod
```


```{r}
mod <- geocodeFile %>% filter(!is.na(latitude))
mod
set.seed(343)
shuf <- sample(nrow(mod))
mod <- mod[shuf,]

train <- sample(nrow(mod)*.80)
bostonTrain <- mod[train,]
bostonTest <- mod[-train,]

length(unique(mod$Area))
length(unique(bostonTrain$Area))
length(unique(bostonTest$Area))

length(unique(mod$longitude))
```


Random Forest

```{r}
bag <- randomForest(Area ~ longitude + latitude + year + totalrooms + type, data = bostonTrain, ntree = 500, mtry = 3, importance = TRUE)
yhat.rf <- predict(bag, newdata = bostonTest)
misclassRate <- mean(yhat.rf != bostonTest$Area)
misclassRate
```


```{r}
options(max.print = 999999999)
table(observed = bostonTest$Area, predicted = yhat.rf)
```

