---
title: "Kmeans"
author: "Bill Lang"
date: "7/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggmap)
```

```{r}
load(file = "cleanBoston.RData")
bostonData
```

```{r}
noNA = bostonData %>% filter(!is.na(latitude) & !is.na(capitalizedPrice))
averages <- noNA %>% group_by(Area) %>% summarise(
                                             meanPrice = mean(capitalizedPrice),
                                             meanLat = mean(latitude),
                                             meanLon = mean(longitude)) %>% select(-Area)

averages
averages<-averages %>% filter(meanLon > -73) %>% filter(meanLon < -69)
averages<-averages %>% filter(meanLat > 41) %>% filter(meanLat < 44)
x <- averages

x$meanPrice = scale(x$meanPrice)
x$meanLat = scale(x$meanLat)
x$meanLon = scale(x$meanLon)

x$meanLat = 3*x$meanLat
x$meanLon = 3*x$meanLon

x
mod <- kmeans(x,50)

z <- as.data.frame(x = mod$cluster)  
names(z)[1] <- c("class")
z$class <- as.factor(z$class)
z
y <- cbind(averages,z)
y
```




```{r}
k <- "AIzaSyDNMoGGfgl9f5KtGCnp9BegNb7ZDqPu7gg"
register_google(key = k)
```


```{r}
map <- get_map(location = 'Boston', zoom = 11, maptype = "terrain-background", source = 'google', color = 'color')
ggmap(map) + geom_point(data = y, mapping = aes(x = meanLon, y = meanLat,color = factor(class)), size = 2) + theme(legend.position = "none")
```

```{r}
map <- get_map(location = 'Boston', zoom = 8, maptype = "terrain-background", source = 'google', color = 'color')
m <- ggmap(map)
```


```{r}
#m + geom_polygon(data = modelData, mapping = aes(x = longitude, y = latitude, fill = capitalizedPrice, group = Area), color = "red", alpha= 0.5)

a <- bostonData %>% filter(capitalizedPrice < 250000)
m + geom_point(data = a, mapping = aes(x = longitude, y = latitude, color = capitalizedPrice)) + scale_colour_gradient(low = "white", high = "blue")

#m + geom_density_2d(data = bostonData, mapping = aes(x = longitude, y = latitude, alpha = capitalizedPrice))
?ggmap
```

