---
title: "KNN"
author: "Bill Lang"
date: "6/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(class)
library(tree)
library(randomForest)
library(glmnet)
library(ggmap)
```

```{r}
bostonArea <- geocodeFile %>% filter(!is.na(latitude))
bostonArea <- bostonArea %>% dplyr::select(Area, totalrooms, longitude, latitude)
bostonArea
```


```{r}
set.seed(343)

shuffleRows <- sample(nrow(bostonArea))
bostonArea <- bostonArea[shuffleRows,]

train <- sample(nrow(bostonArea)*.8)

bostonTrain <- bostonArea[train,]
bostonTest <- bostonArea[-train,] 

bostonTrain.x <- bostonTrain[,-1]
bostonTrain.y <- bostonTrain[,-c(2:4)]
bostonTest.x <- bostonTest[,-1]
bostonTest.y <- bostonTest[,-c(2:4)]
```


```{r}
dim(bostonTrain.x)
length(bostonTrain.y)

dim(bostonTest.x)
length(bostonTest.y)
```


```{r}
bostonTrain.x 
bostonTrain.y

bostonTest.x
bostonTest.y
```

```{r}
all <- c(1:100)
for(i in 1:100){
knn.pred <- knn(train = bostonTrain.x, test = bostonTest.x, cl = bostonTrain.y, k = i)
all[i] <- mean(knn.pred != bostonTest.y)
}

min(all)
hist(all, 100)
which.min(all)

misclassRate <- mean(knn.pred != bostonTest.y)
misclassRate
```

