---
title: "Random Forest"
author: "Bill Lang"
date: "6/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(class)
library(tree)
library(randomForest)
library(glmnet)
library(ggmap)
```


```{r}
str(bostonPrediction)
bostonPrediction$type <-  as.factor(bostonPrediction$type)

unique(bostonPrediction$type)



#Taking only the top results
bostonPrediction %>% group_by(type) %>% summarise(count = n()) %>% arrange(count)
bostonPrediction <- bostonPrediction %>% filter(type == c("suite","ranch","apartment","house"))
bostonPrediction$type <- as.character(bostonPrediction$type)
bostonPrediction$type <- as.factor(bostonPrediction$type)
str(bostonPrediction)

#5 is the mean of totalrooms
bostonPrediction <- bostonPrediction %>% mutate(totalrooms = replace_na(totalrooms,5))

```


```{r}
bostonArea <- bostonPrediction %>% filter(saleprice != 0)
bostonArea
set.seed(343)
train <- sample(nrow(bostonArea)*.8)
bostonTrain <- bostonArea[train,]
bostonTest <- bostonArea[-train,]

length(unique(mod$target_no))
length(unique(bostonTrain$target_no))
length(unique(bostonTest$target_no))
```

```{r}
bag <- randomForest(target_no ~ distance_to_center + angle_from_center + year, data = bostonTrain, ntree = 1000, mtry = 2, importance = TRUE)
yhat.rf <- predict(bag, newdata = bostonTest)
misclassRate <- mean(yhat.rf != bostonTest$target_no)
misclassRate
```


```{r}
options(max.print = 999999999)
table(observed = bostonTest$target_no, predicted = yhat.rf)
```

