---
title: "Building Dataset Output Detroit"
author: "Bill Lang"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Load in the rows that already had a top area

```{r}
load(file = "DetroitTop.RData")
detroitTop = detroitAddress %>% mutate(calculatedColumn = location)
detroitTop
```

Load in the rows we predicted

```{r}
load(file = "predictedDetroit.RData")
predicted
```

```{r}
detroitExport = rbind(detroitTop,predicted)
detroitExport = detroitExport %>% select(-c(X,X.1))
detroitExport = detroitExport %>% select(ï..Transciber:Area,Hse.No:location,Address,latitude:calculatedColumn)
detroitExport
``` 


Load in the rows we could not geocode

```{r}
load(file = "notGeocoded.RData")
notGeocoded = notGeocoded %>% select(-c(X,X.1))
```


```{r}
notGeocoded = notGeocoded %>% select(ï..Transciber:Area,Hse.No:location,Address,latitude,longitude)
notGeocoded
```


Capitalize the Rent. Replace few NAs with the median

```{r}
notGeocoded <- capitalizeRent(notGeocoded)
notGeocoded$capitalizedPrice[is.na(notGeocoded$capitalizedPrice)] = median(notGeocoded$capitalizedPrice[!is.na(notGeocoded$capitalizedPrice)])
#This output should be NA
notGeocoded %>% filter(is.na(capitalizedPrice))
```

Fix columns that will be used in a model. Standardizing the case, setting factors, etc. 

```{r}
notGeocoded$location <- as.factor(notGeocoded$location)

notGeocoded$Price.type <- tolower(notGeocoded$Price.type)
notGeocoded$Price.type <- gsub('income', 'rent', notGeocoded$Price.type)
notGeocoded$Price.type <- as.factor(notGeocoded$Price.type)

notGeocoded$Type <- tolower(notGeocoded$Type)
notGeocoded$Type <- as.factor(notGeocoded$Type)

notGeocoded$Column <- tolower(notGeocoded$Column)
```


Creating a regression for total rooms calculation

```{r}

dim(notGeocoded %>% filter(Total.rooms != ""))[1] #rows with total rooms
dim(notGeocoded %>% filter(Bedrooms != ""))[1]    #rows with bedrooms

data = notGeocoded %>% filter(Bedrooms != "" & Total.rooms != "") #obs with both for model

plot(data$Bedrooms,data$Total.rooms)
model <- lm(Total.rooms ~ Bedrooms, data)

coeff = model$coefficients
names(coeff) <- NULL
multiple = coeff[2]
multiple 


estimation = data.frame(notGeocoded$Total.rooms, notGeocoded$Bedrooms, Total.rooms.estimation = NA) %>% mutate(Total.rooms.estimation = ifelse(!is.na(notGeocoded.Total.rooms), notGeocoded.Total.rooms,round(notGeocoded.Bedrooms*multiple))) 

#fill the rest in with the median

medianOfTotal = median(estimation$Total.rooms.estimation[which(!is.na(estimation$Total.rooms.estimation))])

estimation = estimation %>% mutate(Total.rooms.estimation = ifelse(is.na(Total.rooms.estimation), medianOfTotal,as.double(Total.rooms.estimation))) 

notGeocoded = cbind(notGeocoded, "Total.rooms.estimation"= estimation[,3])
notGeocoded = notGeocoded %>% add_column(calculatedColumn = "")
```


```{r}
detroitExport = rbind(detroitExport,notGeocoded)
```

```{r}
detroitExport
save(detroitExport, file = "detroitExport.RData")
write.csv(detroitExport, file = "C:/Users/the36/Desktop/DataRA/RExports/DetroitExport.csv",row.names=FALSE)
```

