---
title: "Data Cleaning Detroit"
author: "Bill Lang"
date: "10/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggmap)
```

Capitalization Function 

```{r}
capitalizeRent <- function(dataFrame){
  
  dataFrame$Frequency <- as.character(dataFrame$Frequency)
  dataFrame$numericFrequency <- ifelse(grepl(pattern = "m",dataFrame$Frequency), 12, 
                            ifelse(grepl(pattern = "year",dataFrame$Frequency), 1,
                            ifelse(grepl(pattern = "ann",dataFrame$Frequency), 1,
                            ifelse(grepl(pattern = "week",dataFrame$Frequency),52, 12))))
  
  load(file = "Capitalization.RData")
  dataFrame <- dataFrame %>% left_join(capitalizationRate, by = c("Year" = "year"))
  
  dataFrame$Sale.price <- as.numeric(gsub(",","",dataFrame$Sale.price))
  dataFrame$Rent.price <- as.numeric(gsub(",","",dataFrame$Rent.price))
  
  dataFrame$capitalizedPrice <- ifelse( (!is.na(dataFrame$Sale.price) & (dataFrame$Sale.price != "") ), 
                                        dataFrame$Sale.price, 
                                        dataFrame$numericFrequency*dataFrame$cap*dataFrame$Rent.price)
  
  dataFrame$capitalizedPrice <- round(dataFrame$capitalizedPrice,2)
  return(dataFrame)
}
```

Cleaning the Dataset. Pulling in an already Geocoded Dataset.

```{r}
load(file = "detroitGeocoded.RData")

detroitGeocoded
```

Capitalize the Rent. Replace few NAs with the median

```{r}
detroitData <- capitalizeRent(detroitGeocoded)
detroitData$capitalizedPrice[is.na(detroitData$capitalizedPrice)] = median(detroitData$capitalizedPrice[!is.na(detroitData$capitalizedPrice)])
detroitData %>% filter(is.na(capitalizedPrice))
#This should output NA since there should be no empty slots
```

Fix columns that will be used in a model. Standardizing the case, setting factors, etc. 

```{r}
detroitData$location <- as.factor(detroitData$location)

detroitData$Price.type <- tolower(detroitData$Price.type)
detroitData$Price.type <- gsub('income', 'rent', detroitData$Price.type)
detroitData$Price.type <- as.factor(detroitData$Price.type)

detroitData$Type <- tolower(detroitData$Type)
detroitData$Type <- as.factor(detroitData$Type)

detroitData$Column <- tolower(detroitData$Column)
```


Creating a regression for total rooms calculation

```{r}

dim(detroitData %>% filter(Total.rooms != ""))[1] #rows with total rooms
dim(detroitData %>% filter(Bedrooms != ""))[1]    #rows with bedrooms

data = detroitData %>% filter(Bedrooms != "" & Total.rooms != "") #obs with both for model

plot(data$Bedrooms,data$Total.rooms)
model <- lm(Total.rooms ~ Bedrooms, data)

coeff = model$coefficients
names(coeff) <- NULL
multiple = coeff[2]
multiple 


estimation = data.frame(detroitData$Total.rooms, detroitData$Bedrooms, Total.rooms.estimation = NA) %>% mutate(Total.rooms.estimation = ifelse(!is.na(detroitData.Total.rooms), detroitData.Total.rooms,round(detroitData.Bedrooms*multiple))) 

#fill the rest in with the median

medianOfTotal = median(estimation$Total.rooms.estimation[which(!is.na(estimation$Total.rooms.estimation))])

estimation = estimation %>% mutate(Total.rooms.estimation = ifelse(is.na(Total.rooms.estimation), medianOfTotal,as.double(Total.rooms.estimation))) 

detroitData = cbind(detroitData, "Total.rooms.estimation"= estimation[,3])
```


```{r}
plot(data$Bedrooms,data$Total.rooms)
abline(model)
hist(detroitData$Total.rooms.estimation, breaks = 100)
```



Removing areas with no information. 

```{r}
detroitData
detroitData <- detroitData %>% filter(longitude != "")
detroitData <- detroitData %>% filter(latitude != "")
detroitData

test = detroitData %>% filter(!( (latitude > 42.30 & latitude < 42.4)  & (longitude < -83.0 & longitude > -83.1)) )
test
detroitData

```

```{r}
cleanDetroit = detroitData
cleanDetroit
save(cleanDetroit, file = "cleanDetroit.RData")
```


```{r}
k <- "AIzaSyDNMoGGfgl9f5KtGCnp9BegNb7ZDqPu7gg"
register_google(key = k)
```


```{r} 
map <- get_map(location = 'Detroit', zoom = 7, maptype = "terrain-background", source = 'google', color = 'color')
ggmap(map) + geom_point(data = test, mapping = aes(x = longitude, y = latitude, color = factor(location)), size = 1) + theme(legend.position = "none")

```



```{r}

```


