---
title: "Testing Random Forest Detroit"
author: "Bill Lang"
date: "10/21/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidygeocoder)
library(ggmap)
```


Predict the regions that are not there.

```{r}
load(file = "cleanDetroit.RData")
cleanDetroit
```

```{r}
load(file = "AreasDetroit.RData")

#We must add back in the center of the city that we had taken out before
centerOfCity = dataDetroit %>% filter(location %in% listOfAreas) %>% filter(( (latitude > 42.30 & latitude < 42.4)  & (longitude < -83.0 & longitude > -83.1)) )

dataDetroit <- cleanDetroit %>% filter(!(Area %in% listOfAreas))

#Add both datasets together
dataDetroit = rbind(dataDetroit, centerOfCity) 

dataDetroit
```

```{r}
dataDetroit <- dataDetroit %>% filter(!is.na(latitude))
dataDetroit
```

Predict the data using the previous model and map the results for validation. 

```{r}
yhat.rf <- predict(fullModel, newdata = dataDetroit)
predicted <- cbind(dataDetroit,yhat.rf)
predicted <- predicted %>% mutate(calculatedColumn = yhat.rf) %>% select(-yhat.rf)
predicted

#Saving for the predicted file
save(predicted, file = "predictedDetroit.RData")
```


```{r}
map <- get_map(location = 'Detroit', zoom = 10 , maptype = "terrain-background", source = 'google', color = 'color')
ggmap(map) + geom_point(data = predicted, mapping = aes(x = longitude, y = latitude, color = factor(calculatedColumn)), size = 1)+ theme(legend.position = "none")
```




Testing just by lat and long

```{r}
yhat.rf <- predict(fullModelLocation, newdata = dallasDataAddress)
predicted <- cbind(dallasDataAddress,yhat.rf)
predicted <- predicted %>% mutate(calculatedColumn = yhat.rf) %>% select(-yhat.rf)
predicted

#Saving for the predicted file
save(predicted, file = "predicctedBoston.RData")
```


```{r}
map <- get_map(location = 'Detroit', zoom = 10 , maptype = "terrain-background", source = 'google', color = 'color')
ggmap(map) + geom_point(data = centerOfCity, mapping = aes(x = longitude, y = latitude), size = .1) #+ theme(legend.position = "none")
```





