---
title: "Data Cleaning"
author: "Bill Lang"
date: "7/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Capitalization Function 

```{r}
capitalizeRent <- function(dataFrame){
  
  dataFrame$Frequency <- as.character(dataFrame$Frequency)
  dataFrame$numericFrequency <- ifelse(grepl(pattern = "m",dataFrame$Frequency), 12, 
                            ifelse(grepl(pattern = "year",dataFrame$Frequency), 1,
                            ifelse(grepl(pattern = "ann",dataFrame$Frequency), 1,
                            ifelse(grepl(pattern = "week",dataFrame$Frequency),52, 12))))
  
  load(file = "Capitalization.RData")
  dataFrame <- dataFrame %>% left_join(capitalizationRate, by = c("Year" = "year"))
  
  dataFrame$Sale.price <- as.numeric(gsub(",","",dataFrame$Sale.price))
  dataFrame$Rent.price <- as.numeric(gsub(",","",dataFrame$Rent.price))
  
  dataFrame$capitalizedPrice <- ifelse( (!is.na(dataFrame$Sale.price) & (dataFrame$Sale.price != "") ), 
                                        dataFrame$Sale.price, 
                                        dataFrame$numericFrequency*dataFrame$cap*dataFrame$Rent.price)
  dataFrame$capitalizedPrice <- round(dataFrame$capitalizedPrice,2)
  return(dataFrame)
}
```

Cleaning the Dataset. Pulling in an already Geocoded Dataset from the 'All Geocoded' File.

```{r}
load(file = "allNY.RData")
geocodedNY
```

We capitalzie the rent and price and standardize it based on the equation above.

```{r}
correctMatches
NYData <- capitalizeRent(correctMatches)
NYData <- NYData %>% filter(!is.na(capitalizedPrice))
NYData
```

Fix columns that will be used in a model. Standardizing the case, setting factors, etc. 

```{r}
NYData$Area <- tolower(NYData$Area)
NYData$Street <- tolower(NYData$Street)

NYData$Area <- as.factor(NYData$Area)

NYData$Price.type <- tolower(NYData$Price.type)
NYData$Price.type <- gsub('income', 'rent', NYData$Price.type)
NYData$Price.type <- as.factor(NYData$Price.type)

NYData$Type <- tolower(NYData$Type)
NYData$Type <- as.factor(NYData$Type)

NYData$Column <- tolower(NYData$Column)
NYData$Totalrooms <- as.integer(NYData$Totalrooms)
```

We save this file to move onto the 'Training Random Forest' File.

```{r}
save(NYData, file = "cleanNY.RData")
```



