---
title: "Split Boston"
author: "Bill Lang"
date: "2/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

```

This is the file to split the boston data to before and after 1950.

Reading in file.

```{r}
load(file = "cleanBoston.RData")
bostonData
```

```{r}
bostonData$Area <- tolower(bostonData$Area)
```


```{r}
bostonData1949 = bostonData %>% filter(Year <= 1949)
bostonData1950 = bostonData %>% filter(Year > 1949)
```


Removing areas with no information. 

```{r}
bostonData1949 <- bostonData1949 %>% filter(Area != "") 
bostonData1950 <- bostonData1950 %>% filter(Area != "") 
bostonData <- bostonData %>% filter(Area != "")
```


Finding the top labeled areas.

```{r}
tbl1949 <- bostonData1949 %>% group_by(Area) %>% summarise(count = n()) %>% arrange(desc(count))
listOfAreas1949 <- tbl1949[1:50,]$Area
listOfAreas1949
tbl1949
```

```{r}
tbl1950 <- bostonData1950 %>% group_by(Area) %>% summarise(count = n()) %>% arrange(desc(count))
listOfAreas1950 <- tbl1950[1:50,]$Area
listOfAreas1950
tbl1950
```


```{r}
#out of 50 top areas
t = intersect(listOfAreas1949,listOfAreas1950)
t
length(t)

```



```{r}
tbl <- bostonData %>% group_by(Area) %>% summarise(count = n()) %>% arrange(desc(count))
listOfAreas <- tbl[1:50,]$Area
listOfAreas
```


```{r}
boston1949 <- bostonData %>% filter(Area %in% listOfAreas1949)
boston1950 <- bostonData %>% filter(Area %in% listOfAreas1950)
bostonAll <- bostonData %>% filter(Area %in% listOfAreas)
```



```{r}
k <- "AIzaSyDNMoGGfgl9f5KtGCnp9BegNb7ZDqPu7gg"
register_google(key = k)
```


```{r}
map <- get_map(location = 'Boston', zoom = 8, maptype = "terrain-background", source = 'google', color = 'color')
ggmap(map) + geom_point(data = boston1949, mapping = aes(x = longitude, y = latitude, color = factor(Area)), size = 1) + theme(legend.position = "none")

map <- get_map(location = 'Boston', zoom = 8, maptype = "terrain-background", source = 'google', color = 'color')
ggmap(map) + geom_point(data = boston1950, mapping = aes(x = longitude, y = latitude, color = factor(Area)), size = 1) + theme(legend.position = "none")

map <- get_map(location = 'Boston', zoom = 8, maptype = "terrain-background", source = 'google', color = 'color')
ggmap(map) + geom_point(data = bostonAll, mapping = aes(x = longitude, y = latitude, color = factor(Area)), size = 1) + theme(legend.position = "none")
```



```{r}

```


```{r}
splitByDecadeImages <- function(dataframe){
  
  listOutput = list()
  listMapOutput = list()
  
  for(year in seq(1900, 2000, by = 10)){
    
  #Split te dataframe by decade  
  dataframeSplit = dataframe %>% filter(Year < year) %>% filter(Year >= year-10)
  
  #Call the top n areas each run
  df <- dataframeSplit %>% group_by(Area) %>% summarise(count = n()) %>% arrange(desc(count))
  df <- df[1:50,]$Area
  
  #add them to the array
  listOutput[[length(listOutput)+1]] = df
  
  }
  
  
  
map <- get_map(location = 'Boston', zoom = 8, maptype = "terrain-background", source = 'google', color = 'color')

  for(i in 1:11){
    
    mapData <- dataframe %>% filter(Area %in% listOutput[i])
    
listMapOutput[[length(listMapOutput) + 1]] = ggmap(map) + geom_point(data = mapData, mapping = aes(x = longitude, y = latitude, color = factor(Area)), size = 1) + theme(legend.position = "none")
    
  }
  
return(listMapOutput)
  
}  


bostonData$Area = as.character(bostonData$Area)

a = splitByDecade(bostonData)

a

length(a)


list = list()


```



