---
title: "Building Dataset Output Dallas"
author: "Bill Lang"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Load in the rows that already had a top area

```{r}
load(file = "dallasTop.RData")
dallasTop = dallasTop %>% mutate(calculatedColumn = location)
dallasTop
```

Load in the rows we predicted

```{r}
load(file = "predictedDallas.RData")
predicted
```

```{r}
dallasExport = rbind(dallasTop,predicted)
dallasExport = dallasExport %>% select(-c(X,X.1))
dallasExport = dallasExport %>% select(ï..Transciber:Area,Hse.No:location,Address,latitude:calculatedColumn)
dallasExport
``` 



Load in the rows we could not geocode

```{r}
load(file = "dallasGeocodedNotFound.RDa")
geocodedDallasNotFound = geocodedDallasNotFound %>% select(-c(X,X.1))
```


```{r}
geocodedDallasNotFound = geocodedDallasNotFound %>% select(ï..Transciber:Area,Hse.No:location,Address,latitude,longitude)
geocodedDallasNotFound
```


Capitalize the Rent. Replace few NAs with the median

```{r}
geocodedDallasNotFound <- capitalizeRent(geocodedDallasNotFound)
geocodedDallasNotFound$capitalizedPrice[is.na(geocodedDallasNotFound$capitalizedPrice)] = median(geocodedDallasNotFound$capitalizedPrice[!is.na(geocodedDallasNotFound$capitalizedPrice)])
geocodedDallasNotFound %>% filter(is.na(capitalizedPrice))
```

Fix columns that will be used in a model. Standardizing the case, setting factors, etc. 

```{r}
geocodedDallasNotFound$location <- as.factor(geocodedDallasNotFound$location)

geocodedDallasNotFound$Price.type <- tolower(geocodedDallasNotFound$Price.type)
geocodedDallasNotFound$Price.type <- gsub('income', 'rent', geocodedDallasNotFound$Price.type)
geocodedDallasNotFound$Price.type <- as.factor(geocodedDallasNotFound$Price.type)

geocodedDallasNotFound$Type <- tolower(geocodedDallasNotFound$Type)
geocodedDallasNotFound$Type <- as.factor(geocodedDallasNotFound$Type)

geocodedDallasNotFound$Column <- tolower(geocodedDallasNotFound$Column)
```


Creating a regression for total rooms calculation

```{r}

dim(geocodedDallasNotFound %>% filter(Total.rooms != ""))[1] #rows with total rooms
dim(geocodedDallasNotFound %>% filter(Bedrooms != ""))[1]    #rows with bedrooms

data = geocodedDallasNotFound %>% filter(Bedrooms != "" & Total.rooms != "") #obs with both for model

plot(data$Bedrooms,data$Total.rooms)
model <- lm(Total.rooms ~ Bedrooms, data)

coeff = model$coefficients
names(coeff) <- NULL
multiple = coeff[2]
multiple 


estimation = data.frame(geocodedDallasNotFound$Total.rooms, geocodedDallasNotFound$Bedrooms, Total.rooms.estimation = NA) %>% mutate(Total.rooms.estimation = ifelse(!is.na(geocodedDallasNotFound.Total.rooms), geocodedDallasNotFound.Total.rooms,round(geocodedDallasNotFound.Bedrooms*multiple))) 

#fill the rest in with the median

medianOfTotal = median(estimation$Total.rooms.estimation[which(!is.na(estimation$Total.rooms.estimation))])

estimation = estimation %>% mutate(Total.rooms.estimation = ifelse(is.na(Total.rooms.estimation), medianOfTotal,as.double(Total.rooms.estimation))) 

geocodedDallasNotFound = cbind(geocodedDallasNotFound, "Total.rooms.estimation"= estimation[,3])
geocodedDallasNotFound = geocodedDallasNotFound %>% add_column(calculatedColumn = "")
```

add the google column

```{r}
geocodedDallasNotFound = geocodedDallasNotFound %>% mutate(google = 0)
geocodedDallasNotFound = geocodedDallasNotFound %>% select(ï..Transciber:longitude,google,numericFrequency:calculatedColumn)
dallasExport 
```


```{r}
dallasExport = rbind(dallasExport,geocodedDallasNotFound)
```

```{r}
write.csv(dallasExport, file = "C:/Users/the36/Desktop/DataRA/RExports/DallasExport.csv",row.names=FALSE)

```

