---
title: "Data Cleaning Dallas"
author: "Bill Lang"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Capitalization Function 

```{r}
capitalizeRent <- function(dataFrame){
  
  dataFrame$Frequency <- as.character(dataFrame$Frequency)
  dataFrame$numericFrequency <- ifelse(grepl(pattern = "m",dataFrame$Frequency), 12, 
                            ifelse(grepl(pattern = "year",dataFrame$Frequency), 1,
                            ifelse(grepl(pattern = "ann",dataFrame$Frequency), 1,
                            ifelse(grepl(pattern = "week",dataFrame$Frequency),52, 12))))
  
  load(file = "Capitalization.RData")
  dataFrame <- dataFrame %>% left_join(capitalizationRate, by = c("Year" = "year"))
  
  dataFrame$Sale.price <- as.numeric(gsub(",","",dataFrame$Sale.price))
  dataFrame$Rent.price <- as.numeric(gsub(",","",dataFrame$Rent.price))
  
  dataFrame$capitalizedPrice <- ifelse( (!is.na(dataFrame$Sale.price) & (dataFrame$Sale.price != "") ), 
                                        dataFrame$Sale.price, 
                                        dataFrame$numericFrequency*dataFrame$cap*dataFrame$Rent.price)
  dataFrame$capitalizedPrice <- round(dataFrame$capitalizedPrice,2)
  return(dataFrame)
}
```

Cleaning the Dataset. Pulling in an already Geocoded Dataset.

```{r}
load(file = "dallasGeocoded2.RData")
dallasGeocoded
```

Capitalize the Rent. Replace few NAs with the median

```{r}
dallasData <- capitalizeRent(dallasGeocoded)
dallasData$capitalizedPrice[is.na(dallasData$capitalizedPrice)] = median(dallasData$capitalizedPrice[!is.na(dallasData$capitalizedPrice)])
dallasData %>% filter(is.na(capitalizedPrice))
```

Fix columns that will be used in a model. Standardizing the case, setting factors, etc. 

```{r}
dallasData$location <- as.factor(dallasData$location)

dallasData$Price.type <- tolower(dallasData$Price.type)
dallasData$Price.type <- gsub('income', 'rent', dallasData$Price.type)
dallasData$Price.type <- as.factor(dallasData$Price.type)

dallasData$Type <- tolower(dallasData$Type)
dallasData$Type <- as.factor(dallasData$Type)

dallasData$Column <- tolower(dallasData$Column)
```


Creating a regression for total rooms calculation

```{r}

dim(dallasData %>% filter(Total.rooms != ""))[1] #rows with total rooms
dim(dallasData %>% filter(Bedrooms != ""))[1]    #rows with bedrooms

data = dallasData %>% filter(Bedrooms != "" & Total.rooms != "") #obs with both for model

plot(data$Bedrooms,data$Total.rooms)
model <- lm(Total.rooms ~ Bedrooms, data)

coeff = model$coefficients
names(coeff) <- NULL
multiple = coeff[2]
multiple 


estimation = data.frame(dallasData$Total.rooms, dallasData$Bedrooms, Total.rooms.estimation = NA) %>% mutate(Total.rooms.estimation = ifelse(!is.na(dallasData.Total.rooms), dallasData.Total.rooms,round(dallasData.Bedrooms*multiple))) 

#fill the rest in with the median

medianOfTotal = median(estimation$Total.rooms.estimation[which(!is.na(estimation$Total.rooms.estimation))])

estimation = estimation %>% mutate(Total.rooms.estimation = ifelse(is.na(Total.rooms.estimation), medianOfTotal,as.double(Total.rooms.estimation))) 

dallasData = cbind(dallasData, "Total.rooms.estimation"= estimation[,3])
```


```{r}
plot(data$Bedrooms,data$Total.rooms)
abline(model)
```


```{r}
dallasData = dallasData %>% filter(!is.na(latitude))%>% filter(!is.na(longitude))

save(dallasData, file = "cleanDallas.RData")
```



